# Generated by Django 5.2.12 on 2026-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_client_is_active_alter_horse_owner_alter_job_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
