# Generated by Django 5.2.12 on 2026-04-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_job_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobLineItem',
            new_name='LineItem',
        ),
    ]
