# Generated by Django 5.2.12 on 2026-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_joblineitem_lineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
