# Generated by Django 5.2.12 on 2026-04-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_client_created_at_client_updated_at_horse_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='next_appointment',
        ),
        migrations.AddField(
            model_name='job',
            name='appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
