# Generated by Django 5.2.12 on 2026-04-14 04:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_job_date_remove_job_next_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
